In [5]:
import pandas as pd

In [1]:
import pysd

# Load the Vensim model
model = pysd.read_vensim('scenario_ditoooooo.mdl')
model.doc

,Real Name,Py Name,Subscripts,Units,Limits,Type,Subtype,Comment
0,"""Block D-Alpha Natural Gas Reserves""",block_dalpha_natural_gas_reserves,None,TCF,"(nan, nan)",Stateful,Integ,None
1,"""Initial Value of Block D-Alpha Gas Reserves""",initial_value_of_block_dalpha_gas_reserves,None,TCF,"(nan, nan)",Auxiliary,Normal,None
2,"""Non-Tax Indonesia State Income""",nontax_indonesia_state_income,None,Rupiah/Percentage,"(nan, nan)",Constant,Normal,None
3,"""State Revenue (Tax)""",state_revenue_tax,None,Rupiah,"(nan, nan)",Constant,Normal,None
4,Age of Reef and Deep Sea Fish,age_of_reef_and_deep_sea_fish,None,Month,"(nan, nan)",Constant,Normal,None
...,...,...,...,...,...,...,...,...
214,Unit Deploy,unit_deploy,None,Percentage,"(nan, nan)",Auxiliary,Normal,None
215,Utilization of Gas within the area,utilization_of_gas_within_the_area,None,TCF/Month,"(nan, nan)",Constant,Normal,None
216,Utilization of Oil within the area,utilization_of_oil_within_the_area,None,Barrel/Month,"(nan, nan)",Constant,Normal,None
217,Warships Strength,warships_strength,None,Percentage,"(nan, nan)",Auxiliary,Normal,None
218,Workforce Quality,workforce_quality,None,Percentage,"(nan, nan)",Auxiliary,Normal,None

In [2]:
result = model.run()
result

,FINAL TIME,INITIAL TIME,SAVEPER,TIME STEP,Workforce Quality,Effect of Billateral Cooperation,Military Impact,Global Defense Partnership,Modernization and Acquisition of Warships,Economic Approach with China,...,Natural Disasters Level of Threats,Non Military Risk Level,Number of Cyber Attack,Number of Hybrid Threats,Number of Military Threats,Number of Non Military Threats,Social Media Level of Threats,Risk Level Maximum Score,Proxy Level of Threats,Smuggling Level of Threats
time,,,,,,,,,,,,,,,,,,,,,
1,132,1,1,1,4.772604,0,60.000000,0,0,0.0,...,4.114179,0.619395,5,3,5,6,4.446285,9,6.292474,5.195400
2,132,1,1,1,2.891732,0,59.864854,0,0,0.0,...,5.062386,0.554285,5,3,5,6,7.639699,9,5.404201,2.368707
3,132,1,1,1,3.241201,0,59.810757,0,0,0.0,...,7.169470,0.705668,5,3,5,6,4.585206,9,6.643524,7.780891
4,132,1,1,1,4.361161,0,59.713790,0,0,0.0,...,5.799254,0.633669,5,3,5,6,6.097897,9,3.475726,5.766049
5,132,1,1,1,1.789682,0,59.702002,0,0,0.0,...,7.395774,0.601823,5,3,5,6,4.010716,9,6.669362,4.752221
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128,132,1,1,1,3.388187,0.0,57.121283,0,0,0.0,...,8.930396,0.610871,5,3,5,6,4.032731,9,4.895081,4.873896
129,132,1,1,1,1.977629,0.0,57.154109,0,0,0.0,...,4.653921,0.608516,5,3,5,6,5.737807,9,6.422980,2.671994
130,132,1,1,1,4.690266,0.0,57.024521,0,0,0.0,...,6.780867,0.616401,5,3,5,6,6.324426,9,5.939538,6.318069
131,132,1,1,1,3.679169,0.0,56.975498,0,0,0.0,...,2.833732,0.600525,5,3,5,6,7.372853,9,5.582594,5.138560
132,132,1,1,1,3.751443,0.0,56.950389,0,0,0.0,...,4.986976,0.600777,5,3,5,6,5.561833,9,6.114475,3.885581

In [3]:
result.to_excel('output.xlsx')